# Generated by Django 4.1.6 on 2023-04-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
