# Generated by Django 4.1.6 on 2023-04-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bill_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Expired', 'Expired'), ('Refund', 'Refund'), ('Refund Partially', 'Refundpartially')], default='New', max_length=16),
        ),
    ]
