# Generated by Django 4.1.6 on 2023-05-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
        ('payments', '0003_alter_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='orders.order'),
        ),
    ]
