version: '3'

services:
  carrental:
    container_name: carrental
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - carrental-db
      - carrental-redis
    volumes:
      - carrental_media:/media
      - carrental_static:/static
    command: /start-django
    expose:
      - 8000
    ports:
      - '9000:8000'

  carrental-db:
    container_name: carrental-db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123
    volumes:
      - carrental_db_data:/var/lib/postgresql/data
    ports:
      - '6543:5432'

  carrental-redis:
    container_name: carrental-redis
    restart: always
    image: redis:7
    ports:
      - '6379:6379'

  carrental-celery:
    container_name: carrental-celery
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://carrental-redis:6379
      - CELERY_RESULT_BACKEND=redis://carrental-redis:6379
      - CELERY_IMPORTS = ('users.tasks', )
    depends_on:
      - carrental
      - carrental-redis
    volumes:
      - .:/app
    command: celery -A celery worker --loglevel=INFO

volumes:
  carrental_db_data: { }
  carrental_media: { }
  carrental_static: { }