# Generated by Django 4.1.6 on 2023-05-04 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('front_image', models.ImageField(upload_to='car_damage_detection/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Front Image')),
                ('left_image', models.ImageField(upload_to='car_damage_detection/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Left Image')),
                ('right_image', models.ImageField(upload_to='car_damage_detection/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Right Image')),
                ('back_image', models.ImageField(upload_to='car_damage_detection/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Back Image')),
                ('status', models.CharField(blank=True, choices=[('No Damage', 'Nodamage'), ('Damaged', 'Damaged')], max_length=9, null=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_detection', to='orders.order')),
            ],
        ),
    ]
