# Generated by Django 4.1.6 on 2023-05-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damage_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagedetection',
            options={'ordering': ('-created_at',), 'verbose_name': 'Damage Detection', 'verbose_name_plural': 'Damage Detections'},
        ),
    ]
