# Generated by Django 4.1.6 on 2023-05-08 21:12

import damage_detection.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage_detection', '0002_alter_damagedetection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedetection',
            name='back_image',
            field=models.ImageField(upload_to=damage_detection.models.car_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Back Image'),
        ),
        migrations.AlterField(
            model_name='damagedetection',
            name='front_image',
            field=models.ImageField(upload_to=damage_detection.models.car_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Front Image'),
        ),
        migrations.AlterField(
            model_name='damagedetection',
            name='left_image',
            field=models.ImageField(upload_to=damage_detection.models.car_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Left Image'),
        ),
        migrations.AlterField(
            model_name='damagedetection',
            name='right_image',
            field=models.ImageField(upload_to=damage_detection.models.car_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Right Image'),
        ),
    ]
