# Generated by Django 4.1.6 on 2023-04-19 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('main_image', models.ImageField(upload_to='cars/', verbose_name='Main Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ('-created_at',),
            },
        ),
    ]
