# Generated by Django 4.1.6 on 2023-04-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=14),
            preserve_default=False,
        ),
    ]
