# Generated by Django 4.1.6 on 2023-04-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_car_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Almaty', 'Almaty'), ('Astana', 'Astana'), ('Shymkent', 'Shymkent'), ('Karaganda', 'Karaganda'), ('Taraz', 'Taraz'), ('Aqtobe', 'Aqtobe')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_centers', to='cars.car')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
