# Generated by Django 4.1.6 on 2023-04-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_amount'),
        ('rental_centers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcenter',
            name='car',
        ),
        migrations.AddField(
            model_name='rentalcenter',
            name='car',
            field=models.ManyToManyField(related_name='rental_centers', to='cars.car'),
        ),
    ]
