# Generated by Django 4.1.6 on 2023-04-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_centers', '0002_remove_rentalcenter_car_rentalcenter_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalcenter',
            options={'ordering': ('-created_at',), 'verbose_name': 'Rental Center', 'verbose_name_plural': 'Rental Centers'},
        ),
        migrations.RenameField(
            model_name='rentalcenter',
            old_name='car',
            new_name='cars',
        ),
        migrations.AlterField(
            model_name='rentalcenter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='rentalcenter',
            name='location',
            field=models.CharField(choices=[('Almaty', 'Almaty'), ('Astana', 'Astana'), ('Shymkent', 'Shymkent'), ('Karaganda', 'Karaganda'), ('Taraz', 'Taraz'), ('Aqtobe', 'Aqtobe')], max_length=15, verbose_name='Location'),
        ),
    ]
