# Generated by Django 4.1.6 on 2023-04-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_centers', '0003_alter_rentalcenter_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalcenter',
            old_name='cars',
            new_name='car',
        ),
    ]
