# Generated by Django 4.1.6 on 2023-04-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_centers', '0004_rename_cars_rentalcenter_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalcenter',
            old_name='car',
            new_name='cars',
        ),
    ]
