# Generated by Django 4.1.6 on 2023-04-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_centers', '0005_rename_car_rentalcenter_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcenter',
            name='location',
            field=models.CharField(choices=[('Almaty', 'Almaty'), ('Astana', 'Astana'), ('Shymkent', 'Shymkent'), ('Karaganda', 'Karaganda'), ('Taraz', 'Taraz'), ('Aqtobe', 'Aqtobe')], max_length=15, unique=True, verbose_name='Location'),
        ),
    ]
