# Generated by Django 4.1.6 on 2023-04-23 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_centers', '0005_rename_car_rentalcenter_cars'),
        ('cars', '0002_car_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('ProcessInProgress', 'Processinprogress'), ('Cancel', 'Cancel'), ('Paid', 'Paid')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField(verbose_name='Pick-up date')),
                ('drop_off_date', models.DateField(verbose_name='Drop-off date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('car', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='cars.car')),
                ('drop_off_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drop_off_location', to='rental_centers.rentalcenter', verbose_name='Drop-off Location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.order')),
                ('pick_up_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_up_location', to='rental_centers.rentalcenter', verbose_name='Pick-up Location')),
            ],
        ),
    ]
