# Generated by Django 4.1.6 on 2023-04-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_amount'),
        ('orders', '0002_alter_orderitem_drop_off_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('ProcessInProgress', 'Processinprogress'), ('Cancel', 'Cancel'), ('Paid', 'Paid'), ('Delivered', 'Delivered')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='car',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='orders.order'),
        ),
    ]
