# Generated by Django 4.1.6 on 2023-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('ProcessInProgress', 'Processinprogress'), ('Damaged', 'Damaged'), ('Cancel', 'Cancel'), ('Paid', 'Paid'), ('Delivered', 'Delivered')], default='New', max_length=20),
        ),
    ]
